### PR TITLE
Style form like design

### PR DESCRIPTION
**Pull request by meshy**

### CODE REVIEW

**Comment by pandalion** [comment]
@ghickman can we add placeholder text to the form fields? Think we will use this instead of labels so it will be replaced when user clicks on them in the form.
(alternatively is this something I should do with javascript?)

**Comment by ghickman** [comment]
html5 placeholder!

I think @perry or @meshy would be best to speak to about form stuff.

**Comment by pandalion** [comment]
Yeah, I meant that I can't get to the form fields to add the html5 placeholder :)

**Comment by ghickman** [comment]
You can either build the form elements yourself or use one of the libraries, but @perry or @meshy are best to speak to!

**Comment by meshy** [comment]
Just finishing off some crispy forms stuff! -- will hop onto that in 10.

**Comment by pandalion** [comment]
@meshy list of fields..
Name
Email address
GitHub User (Optional)
Anything else? Dietary requirements etc.

(as placeholders) 
thanks!

**Comment by pandalion** [comment]
@meshy please could you do (or show me how to) limit textarea rows to maybe 5 rows? May need to adjust styling in a minor way following that.

**Comment by pandalion** [comment]
cool, thank you @perry !

**Pull request merged**
